#!/usr/bin/env bash

# TODO (Run this script as): color magenta && echo hello && color reset

color() {
    echo -ne "\033[$1;$2m"
}

declare -A color_mapping=(
    
    # added more color values
    ['magenta']=35
    ['blue']=34
    ['yellow']=33
    ['green']=32
    ['cyan']=36
    ['white']=37
)

if [[ $1 == 'reset' ]]; then
    color 0 00
else
    color 1 ${color_mapping[$1]}
fi

